import Head from 'next/head';
import Home from '../components/home/Home';
// import Corral from '../components/corral/Corral';
import styles from '../styles/Home.module.css';

export default function HomePage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kitty Corral</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        Home Page
        <Home />
      </main>
    </div>
  )
}
